name: Bot Health Check
on:
  schedule:
    - cron: '*/5 * * * *'  # Проверка каждые 5 минут
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the bot
        run: |
          RESPONSE=$(curl -s "URL_ВАШЕГО_БОТА/health")
          if [[ "$RESPONSE" != *"OK"* ]]; then
            echo "Bot is down!"
            # Оповещение в Telegram (пример)
            curl -s "https://api.telegram.org/botTELEGRAM_BOT_TOKEN/sendMessage?chat_id=CHAT_ID&text=Бот%20не%20отвечает!"
            exit 1
          fi
